name = "ipproxycontroller"
main = "src/index.js"
compatibility_date = "2026-06-03"

# 告诉 Cloudflare 这是一个普通的 Worker
workers_dev = true

# 声明代码中用到的环境变量（用户在部署页面或稍后可以修改）
[vars]
WEB_USER = "admin"
WEB_PASS = "admin888"
PROXY_USER = "proxy"
PROXY_PASS = "888888"

# 声明 D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "proxy_db"
database_id = "cbbc92a6-24d5-43ff-9256-1ce6fa2e367b" # 留空，一键部署向导或后续配置会引导用户绑定他们自己的 D1 数据库
